From: Victor Stinner <vstinner@python.org>
Date: Wed, 6 Jan 2021 10:07:29 +0100
Subject: [PATCH] Fix compatibility with Python 3.10.0a4: fopen

Replace private _Py_fopen() with public fopen(): private _Py_fopen()
function was removed in 3.10.0a4:
https://bugs.python.org/issue32381
---
 libs/python/src/exec.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/libs/python/src/exec.cpp b/libs/python/src/exec.cpp
index 171c6f4189b9..43e860d992b1 100644
--- a/libs/python/src/exec.cpp
+++ b/libs/python/src/exec.cpp
@@ -106,7 +106,7 @@ object BOOST_PYTHON_DECL exec_file(char const *filename, object global, object l
   char *f = const_cast<char *>(filename);
   // Let python open the file to avoid potential binary incompatibilities.
 #if PY_VERSION_HEX >= 0x03040000
-  FILE *fs = _Py_fopen(f, "r");
+  FILE *fs = fopen(f, "r");
 #elif PY_VERSION_HEX >= 0x03000000
   PyObject *fo = Py_BuildValue("s", f);
   FILE *fs = _Py_fopen(fo, "r");
